### ISSUE TITLE
name 'xarray' is not defined

### ISSUE THREAD

**Issue by junweihua** [malmans2/oceanspy#467]
when i try to convert the xarray.dataset to oceanspy.OceanDataset,
An error occurred says that name xarray is not defined

import xarray as xr
import xarray
import glob
variable='u'
winter_list=glob.glob(f'../GoM/hycom_2023-01*_{variable}.nc')+glob.glob(f'../GoM/hycom_2023-02*_{variable}.nc')
summer_list=glob.glob(f'../GoM/hycom_2023-06*_{variable}.nc')+glob.glob(f'../GoM/hycom_2023-07*_{variable}.nc')+glob.glob(f'../GoM/hycom_2023-08*_{variable}.nc')
ds_winter=xr.open_dataset(winter_list[0]).load()
import oceanspy as ospy
od_winter = ospy.OceanDataset(ds_winter)

**Comment by junweihua** [comment]
I already installed xarray

**Comment by ThomasHaine** [comment]
Hi @junweihua . Are you working with [OceanSpy on SciServer](https://oceanspy.readthedocs.io/en/latest/sciserver.html), or your own machine?  The SciServer environment is preconfigured and shouldn't give any trouble. If you're working on your own machine, you'll need to configure and activate the environment correctly by following [these instructions](https://oceanspy.readthedocs.io/en/latest/installation.html).

**Comment by junweihua** [comment]
Thanks for reply, im working on my own machine, formerly I used python 3.13 and used pip install, now i configured the environment used conda install, I cannot import oceanspy. My computer is macpro.
[1](vscode-notebook-cell:?execution_count=1&line=1) import xarray as xr
----> [2](vscode-notebook-cell:?execution_count=1&line=2) import oceanspy as osp

File /opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:3
      [1](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:1) import numpy as _np
----> [3](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:3) from . import (
      [4](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:4)     _ospy_utils,
      [5](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:5)     animate,
      [6](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:6)     compute,
      [7](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:7)     llc_rearrange,
      [8](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:8)     open_oceandataset,
      [9](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:9)     plot,
     [10](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:10)     subsample,
     [11](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:11)     utils,
     [12](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:12) )
     [13](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:13) from ._oceandataset import OceanDataset
     [15](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:15) try:
     [16](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:16)     # NOTE: the `version.py` file must not be present in the git repository
     [17](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/__init__.py:17)     #   as it is generated by setuptools at install time

File /opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/animate.py:24
     [21](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/animate.py:21) import oceanspy as _ospy
...
---> [12](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/llc_rearrange.py:12) from shapely import Point, Polygon
     [13](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/llc_rearrange.py:13) from xarray import DataArray, Dataset
     [15](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/llc_rearrange.py:15) from .utils import _rel_lon, _reset_range, connector, get_maskH, reset_dim

ImportError: cannot import name 'Point' from 'shapely' (/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/shapely/__init__.py)

**Comment by Mikejmnez** [comment]
Hi @junweihua thanks for reaching out! I am just catching up with your issues using oceanspy. 

> An error occurred says that name xarray is not defined

is your issue about xarray resolved?

> ---> [12](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/llc_rearrange.py:12) from shapely import Point, Polygon
[13](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/llc_rearrange.py:13) from xarray import DataArray, Dataset
[15](https://file+.vscode-resource.vscode-cdn.net/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/oceanspy/llc_rearrange.py:15) from .utils import _rel_lon, _reset_range, connector, get_maskH, reset_dim

> ImportError: cannot import name 'Point' from 'shapely' (/opt/anaconda3/envs/oceanspy-env/lib/python3.9/site-packages/shapely/init.py)

It looks like there may be a problem with your `shapely` installation. I ran

```python
from shapely import Point
```
and it works fine with `Python 3.11` and shapely `2.1.0`. What version of python / shapely do you have installed? Or better, can you share your environment? Our ability to reproduce errors is important to diagnose the root of them.

Thanks again!
